use crate::backends::Backend;
use crate::button::{InputEvent, KeyboardInput, apply_shift_to_ascii};
use embedded_graphics_simulator::sdl2::{Keycode, Mod};
use embedded_graphics_simulator::{OutputSettings, SimulatorDisplay, SimulatorEvent, Window};
use mousefood::embedded_graphics::geometry::Size;
use mousefood::{EmbeddedBackend, EmbeddedBackendConfig, prelude::Rgb565};
use std::process::exit;
use std::sync::mpsc::{self, Receiver, Sender};

/// Creates the simulator backend and returns it along with a channel receiver
/// for input events generated by the simulator window.
pub fn setup_simulator_and_input() -> (Backend<SimulatorDisplay<Rgb565>>, Receiver<InputEvent>) {
    println!("Setting up simulator hardware and input");
    let mut simulator_window = Window::new(
        "Simulator",
        &OutputSettings {
            scale: 2,
            ..Default::default()
        },
    );
    let display = SimulatorDisplay::<Rgb565>::new(Size::new(320, 240));
    let (tx, rx) = mpsc::channel();

    let backend_config: EmbeddedBackendConfig<SimulatorDisplay<Rgb565>, _> =
        EmbeddedBackendConfig {
            flush_callback: Box::new(move |display| {
                simulator_window.update(display);

                process_simulator_events(&mut simulator_window, &tx);
            }),
            ..Default::default()
        };

    let backend = EmbeddedBackend::new(Box::leak(Box::new(display)), backend_config);
    (backend, rx)
}

/// Iterates through all available simulator events and dispatches them.
fn process_simulator_events(window: &mut Window, tx: &Sender<InputEvent>) {
    for event in window.events() {
        match event {
            SimulatorEvent::KeyDown { keycode, keymod, .. } => {
                if let Some(input_event) = translate_keydown_event(keycode, keymod) {
                    tx.send(input_event).ok();
                }
            }
            SimulatorEvent::Quit => {
                println!("simulator window closed");
                exit(0);
            }
            _ => { /* Ignore other events */ }
        }
    }
}

fn translate_keydown_event(keycode: Keycode, keymod: Mod) -> Option<InputEvent> {
    match keycode {
        Keycode::Return | Keycode::KpEnter => Some(InputEvent::key(KeyboardInput::Enter)),
        Keycode::Backspace => Some(InputEvent::key(KeyboardInput::Backspace)),
        Keycode::Escape => Some(InputEvent::key(KeyboardInput::Escape)),
        Keycode::Left => Some(InputEvent::key(KeyboardInput::Left)),
        Keycode::Right => Some(InputEvent::key(KeyboardInput::Right)),
        Keycode::Up => Some(InputEvent::key(KeyboardInput::Up)),
        Keycode::Down => Some(InputEvent::key(KeyboardInput::Down)),
        Keycode::Tab => Some(InputEvent::key(if is_shift_pressed(keymod) {
            KeyboardInput::BackTab
        } else {
            KeyboardInput::Tab
        })),
        _ => map_keycode_to_char(keycode).map(|base| {
            InputEvent::key(KeyboardInput::Char(apply_shift_to_ascii(
                base,
                is_shift_pressed(keymod),
                false,
            )))
        }),
    }
}

fn is_shift_pressed(keymod: Mod) -> bool {
    keymod.intersects(Mod::LSHIFTMOD | Mod::RSHIFTMOD)
}

fn map_keycode_to_char(keycode: Keycode) -> Option<char> {
    Some(match keycode {
        Keycode::A => 'a',
        Keycode::B => 'b',
        Keycode::C => 'c',
        Keycode::D => 'd',
        Keycode::E => 'e',
        Keycode::F => 'f',
        Keycode::G => 'g',
        Keycode::H => 'h',
        Keycode::I => 'i',
        Keycode::J => 'j',
        Keycode::K => 'k',
        Keycode::L => 'l',
        Keycode::M => 'm',
        Keycode::N => 'n',
        Keycode::O => 'o',
        Keycode::P => 'p',
        Keycode::Q => 'q',
        Keycode::R => 'r',
        Keycode::S => 's',
        Keycode::T => 't',
        Keycode::U => 'u',
        Keycode::V => 'v',
        Keycode::W => 'w',
        Keycode::X => 'x',
        Keycode::Y => 'y',
        Keycode::Z => 'z',
        Keycode::Num1 => '1',
        Keycode::Num2 => '2',
        Keycode::Num3 => '3',
        Keycode::Num4 => '4',
        Keycode::Num5 => '5',
        Keycode::Num6 => '6',
        Keycode::Num7 => '7',
        Keycode::Num8 => '8',
        Keycode::Num9 => '9',
        Keycode::Num0 => '0',
        Keycode::Space => ' ',
        Keycode::Minus => '-',
        Keycode::Equals => '=',
        Keycode::LeftBracket => '[',
        Keycode::RightBracket => ']',
        Keycode::Backslash => '\\',
        Keycode::Semicolon => ';',
        Keycode::Quote => '\'',
        Keycode::Backquote => '`',
        Keycode::Comma => ',',
        Keycode::Period => '.',
        Keycode::Slash => '/',
        _ => return None,
    })
}
