name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft, ready_for_review]
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    name: Build ${{ matrix.environments.title }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        environments:
          - runner: ubuntu-latest
            title: ubuntu/aarch64-gnu
            setup: sudo apt install -y gcc-aarch64-linux-gnu

          - runner: macos-latest
            title: MacOS/aarch64-gnu
            setup: brew install zig && pip install cargo-zigbuild

    runs-on: ${{ matrix.environments.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run build
        shell: bash
        run: |
          set -e

          if [[ -n "${{ matrix.environments.setup }}" ]]; then
            echo "Running setup command: ${{ matrix.environments.setup }}"
            ${{ matrix.environments.setup }}
          fi

          make build
